export enum FoodRestrictionCompatibility {
  NO_RESTRICTION= "No restriction",
  VEGAN= "Vegan",
  VEGETARIAN= "Vegetarian",
  DIABETIC= "Diabetic",
  GLUTEN_FREE= "Gluten free",
  KETO = "Keto",
  PALEO = "Paleo",
  PESCATARIAN= "Pescatarian",
  DAIRY_FREE= "Dairy free",
  LOW_FAT= "Low fat",
  LOW_SODIUM= "Low sodium",
  LOW_SUGAR= "Low sugar",
  LOW_CARB= "Low carb",
  LOW_CHOLESTEROL= "Low cholesterol",
  LOW_CALORIE= "Low calorie",
  LOW_PROTEIN= "Low protein",
  LOW_FIBER= "Low fiber",
  LOW_POTASSIUM= "Low potassium",
  LOW_SATURATED_FAT= "Low saturated fat",
}
